# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 918d871eccec41f5b0c595b49aa4dc72c199fb7d81b233e6c375146e357dcf595a338c5d4040e1555a58112006fb39335fd0f5a5012b75b370dd12702ef0035f

  stripe_publishable_key: pk_test_OTSDzUcrUDcCngntSiklicLM
  stripe_secret_key: sk_test_7T6oDKnp0hvwcBj5Qhihzctg

test:
  secret_key_base: 962930aa76f028fc8935e8e863283fae7b73b1ae65b539ec98d3ad7b65bc7a0cbcd1ea852e1242d99202774dddc6a897eead2f46851aab67788f394fa9f223eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_secret_key']